# Generated by Django 3.0.8 on 2020-07-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('is_repeter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('hourly', models.IntegerField(default=0)),
                ('each_day', models.IntegerField(default=0)),
                ('weekly', models.IntegerField(default=0)),
                ('each_month', models.IntegerField(default=0)),
                ('each_year', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConsume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('date_payed', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Bill')),
                ('consume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Consume')),
            ],
        ),
        migrations.AddField(
            model_name='consume',
            name='type_consume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.TypeConsume'),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Priority'),
        ),
        migrations.AddField(
            model_name='bill',
            name='repeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Repeter'),
        ),
        migrations.AddField(
            model_name='bill',
            name='type_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.TypeBill'),
        ),
    ]
