# Generated by Django 3.0.8 on 2020-07-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200723_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='consume',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='repeter',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='is_valid',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='typebill',
            old_name='is_valid',
            new_name='is_delete',
        ),
    ]
